### ISSUE TITLE
DF missing latAnth anthropological latent heat parameter?

### ISSUE THREAD

**Issue by saeranv** [chriswmackey/Dragonfly#45]
@chriswmackey ,

I think the latAnth parameter isn't defined in Dragonfly. 

It's one of the required parameters In the Run UWG component it should be defined in the urban characteristics along with the sensible anthro heat:

https://github.com/chriswmackey/Dragonfly/blob/220e5c11de084b9963cb28d0fe278b74e68e59a1/src/DF%20Run%20Urban%20Weather%20Generator.py#L142-L149

i.e here is default used in the singapore paramters file:
```
# Urban characteristics
bldHeight,10,     # average building height (m)
bldDensity,0.5,   # urban area building plan density (0-1)
verToHor,0.8,     # urban area vertical to horizontal ratio
h_mix,1,           # fraction of building HVAC waste heat set to the street canyon [as opposed to the roof]
charLength,1000,  # dimension of a square that encompasses the whole neighborhood [aka. characteristic length] (m)
albRoad,0.1,      # road albedo (0 - 1)
dRoad,0.5,        # road pavement thickness (m)
kRoad,1,          # road pavement conductivity (W/m K)
cRoad,1600000,    # road volumetric heat capacity (J/m^3 K)
sensAnth,20,      # non-building sensible heat at street level [aka. heat from cars, pedestrians, street cooking, etc. ] (W/m^2)
latAnth,2,        # non-building latent heat (W/m^2) (currently not used)
```
Also, the uwg checks to make sure all the inputs are defined correctly here : https://github.com/ladybug-tools/uwg/blob/master/uwg/uwg.py#L435-L482, but I don't think the Run UWG component in DF is calling this method because it's using an alternative method of inputting values.  I can make this into a separate method so DF can use it, so we don't run into this issue again.

**Comment by saeranv** [comment]
Update: I pulled out a separate check_required_parameters method in UWG for this purpose. 

https://github.com/saeranv/uwg/blob/960e479d9f5170e05b4c95cb5f85862c4580ef14/uwg/uwg.py#L437-L469

So you should just be able to add this to the RunUWG component:
```
assert uwg_object.check_required_inputs()
```

To confirm all the required inputs are there.

**Comment by chriswmackey** [comment]
@saeranv ,

I have started to integrate the check but I can't get it to pass even though all of the required inputs seem to be assigned.  It would be extremely helpful to have this function state what input is missing because, otherwise, this function really isn't any more helpful than the alternative.

In fact, I would argue that this function is currently less helpful than the alternative since, at least in the that case, we have some idea of what part of the calculation failed and what types of inputs might be responsible.  Here, I just have no idea.

On a smaller note, this seems like a messy way to write the check since the length of a list will always be an integer:
https://github.com/saeranv/uwg/blob/960e479d9f5170e05b4c95cb5f85862c4580ef14/uwg/uwg.py#L457

And, lastly, I would ask why the latent anthropogenic heat is a required input when it currently has no influence on the calculation?  Are we planning to add moisture balances into the UWG soon?

**Comment by chriswmackey** [comment]
I think that I will hold off on implementing the check function in both the legacy dragonfly and the dragonfly core until the information from the check is more useful.  Let me know if you manage to push such a change, @saeranv , and I will implement it on both repos.

**Comment by saeranv** [comment]
@chriswmackey 

You're right, I completely forgot that we decided to omit the latAnth because it wasn't being used in this version of the uwg. The issue then is not that it's missing from DF, but that it's still a required parameter in the UWG! I'll make sure to remove it. 

And yes, I can change the required parameters methods. I implemented that method as a quick and dirty patch to catch any integers being passed into the UWG when it should be a float, but the time has clearly come to refactor it cleanly. 

The reason it's still useful is that, if you pass an integer into the UWG, it will still do it's calculation and give you an incorrect epw file as a result. It won't just fail, so better a soft fail, then invisibly flawed success. That being said it should be trivial to get it to return the actual parameter that is failing. 

Will make changes when I get the chance!

S

**Comment by chriswmackey** [comment]
@saeranv ,

All makes sense and thank you for the explanation.  I am glad to hear that you will remove latAnth from the UWG since it seems like it will be a while before we can get around to moisture balance calculations.

That would be great if you can improve the required parameters check and you are right that it is better to have the simulation fail rather than return an incorrect success.  I will implement the check function as soon as you push the update.  I think that you can still do the checks with a minimal amount of clean code (it will just take a lot of assert statements).

**Comment by saeranv** [comment]
Done!

There's a PR with the new check_required_inputs method that should solve this. I rewrote everything to simply be a series of assert statements, so it should provide you the info you need to isolate your problem, a lot better now.

I also removed the latAnth from the .uwg sample files in the UWG repo.

**Comment by saeranv** [comment]
I forgot that I had push access to your DF repo, and mistakenly just pushed my refactored UWG code directly into the base/canonical fork. At any rate test it out and let me know how it goes.

**Comment by chriswmackey** [comment]
@saeranv ,
Awesome.  Thanks for doing this and no worries about the direct push (it actually helps me out a bit here).  Let me see if I can add the check into the "Run UWG" component now.

**Comment by chriswmackey** [comment]
@saeranv ,

There were large number of inputs going into the UWG as integers and not floats.  While your new code allowed me to see on what line the assertion failed (and thus deduce which input was wrong), it still isn't the way that I would implement these types of checks since someone who doesn't have the uwg code in font of them is still not going to know what has gone worng.

I changed the checks to be more informative as you see I have committed to this repo here:
https://github.com/chriswmackey/Dragonfly/commit/7a8e3b2b5f2a0f52c919a6bed57b195d1270cace#diff-a226d4381c852ce81325ea5b7180fdc2R441

... and I sent you a PR for the uwg repo to incorporate the same:
https://github.com/ladybug-tools/uwg/pull/93

If you feel that this is a good solution, please merge the PR and I will let you do the honors of closing out this issue :)

**Comment by saeranv** [comment]
Man, I'm humbled by your attention to detail here @chriswmackey. Thanks for making these edits, and I'll up my raised exceptions/assert game next time to match this.

Closed!
